#!/bin/sh

./mvnw clean install -Dmaven.test.skip=true

cd migration/item-migration||exit
docker build -t item-migration .

cd ../../app/item-service||exit
docker build -t item-service .

cd ../reactive-item-service||exit
docker build -t reactive-item-service .

cd ..