version: "3.7"

services:
  postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    ports:
      - 15432:5432
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    command:
      postgres
      -c 'max_connections=600'
      -c 'shared_buffers=1GB'
      -c 'effective_cache_size=3GB'
      -c 'maintenance_work_mem=256MB'
      -c 'checkpoint_completion_target=0.9'
      -c 'wal_buffers=16MB'
      -c 'default_statistics_target=100'
      -c 'random_page_cost=1.1'
      -c 'effective_io_concurrency=200'
      -c 'work_mem=436kB'
      -c 'min_wal_size=2GB'
      -c 'max_wal_size=8GB'
      -c 'max_worker_processes=8'
      -c 'max_parallel_workers_per_gather=4'
      -c 'max_parallel_workers=8'
      -c 'max_parallel_maintenance_workers=4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres/data:/var/lib/postgresql/data/:rw
    deploy:
      resources:
        limits:
          memory: 4g

  item-migration:
    container_name: item-migration
    image: item-migration
    networks:
      - service
    depends_on:
      - postgres
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Dspring.profiles.active=docker
    deploy:
      resources:
        limits:
          memory: 256m

  item-service:
    container_name: item-service
    image: item-service
    ports:
      - 8181:8181
      - 7001:7001
    networks:
      - service
    depends_on:
      - postgres
      - item-migration
    ulimits:
      nproc: 514933
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.rmi.port=7001
        -Dspring.profiles.active=docker
    deploy:
      resources:
        limits:
          memory: 256m

  reactive-item-service:
    container_name: reactive-item-service
    image: reactive-item-service
    ports:
      - 8182:8181
      - 7002:7002
    networks:
      - service
    depends_on:
      - postgres
      - item-migration
    ulimits:
      nproc: 514933
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7002 -Dcom.sun.management.jmxremote.rmi.port=7002
        -Dspring.profiles.active=docker
    deploy:
      resources:
        limits:
          memory: 256m

networks:
  service:
    driver: bridge