version: "3.7"

services:
  item-service:
    container_name: item-service
    image: item-service
    network_mode: host
    extra_hosts:
      - localhost:127.0.0.1
    ulimits:
      nproc: 514933
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.rmi.port=7001
    deploy:
      resources:
        limits:
          memory: 256m

  reactive-item-service-pool:
    container_name: reactive-item-service-pool
    image: reactive-item-service
    network_mode: host
    extra_hosts:
      - localhost:127.0.0.1
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7002 -Dcom.sun.management.jmxremote.rmi.port=7002
        -Dspring.r2dbc.pool.initialSize=50 -Dspring.r2dbc.pool.maxSize=50
    deploy:
      resources:
        limits:
          memory: 256m

  reactive-item-service-wo-pool:
    container_name: reactive-item-service-wo-pool
    image: reactive-item-service
    network_mode: host
    extra_hosts:
      - localhost:127.0.0.1
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_rmem: 4096 87380 134217728
      net.ipv4.tcp_wmem: 4096 87380 134217728
      net.ipv4.tcp_moderate_rcvbuf: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_congestion_control: htcp
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_timestamps: 0
      net.ipv4.tcp_sack: 0
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:+ExitOnOutOfMemoryError
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7003 -Dcom.sun.management.jmxremote.rmi.port=7003
        -Dserver.port=8183
        -Dspring.r2dbc.pool.enabled=false
    deploy:
      resources:
        limits:
          memory: 256m