server:
  port: 8181
spring:
  r2dbc:
    url: r2dbc:${app.datasource.url-suffix}
    username: postgres
    password: postgres
app:
  datasource:
    url-suffix: postgresql://postgres:5432/cleanarchitecture